# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainDetect_UI.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1408, 696)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox_AftShow = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_AftShow.setGeometry(QtCore.QRect(710, 10, 690, 490))
        self.groupBox_AftShow.setObjectName("groupBox_AftShow")
        self.label_AftPicShow = QtWidgets.QLabel(self.groupBox_AftShow)
        self.label_AftPicShow.setGeometry(QtCore.QRect(10, 20, 670, 460))
        self.label_AftPicShow.setText("")
        self.label_AftPicShow.setObjectName("label_AftPicShow")
        self.groupBox_PreShow = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_PreShow.setGeometry(QtCore.QRect(10, 10, 690, 490))
        self.groupBox_PreShow.setObjectName("groupBox_PreShow")
        self.label_PrePicShow = QtWidgets.QLabel(self.groupBox_PreShow)
        self.label_PrePicShow.setGeometry(QtCore.QRect(10, 20, 670, 460))
        self.label_PrePicShow.setText("")
        self.label_PrePicShow.setScaledContents(True)
        self.label_PrePicShow.setObjectName("label_PrePicShow")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(10, 510, 361, 141))
        self.groupBox.setObjectName("groupBox")
        self.label_datatype = QtWidgets.QLabel(self.groupBox)
        self.label_datatype.setGeometry(QtCore.QRect(20, 30, 81, 20))
        self.label_datatype.setObjectName("label_datatype")
        self.comboBox_SelectData = QtWidgets.QComboBox(self.groupBox)
        self.comboBox_SelectData.setGeometry(QtCore.QRect(100, 30, 101, 22))
        self.comboBox_SelectData.setObjectName("comboBox_SelectData")
        self.comboBox_SelectData.addItem("")
        self.comboBox_SelectData.setItemText(0, "")
        self.comboBox_SelectData.addItem("")
        self.comboBox_SelectData.addItem("")
        self.pushButton_3Ddetect = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_3Ddetect.setGeometry(QtCore.QRect(210, 30, 71, 23))
        self.pushButton_3Ddetect.setObjectName("pushButton_3Ddetect")
        self.label_datatype_2 = QtWidgets.QLabel(self.groupBox)
        self.label_datatype_2.setGeometry(QtCore.QRect(20, 70, 81, 21))
        self.label_datatype_2.setObjectName("label_datatype_2")
        self.comboBox_SelectDetect = QtWidgets.QComboBox(self.groupBox)
        self.comboBox_SelectDetect.setGeometry(QtCore.QRect(100, 70, 101, 22))
        self.comboBox_SelectDetect.setObjectName("comboBox_SelectDetect")
        self.comboBox_SelectDetect.addItem("")
        self.comboBox_SelectDetect.setItemText(0, "")
        self.comboBox_SelectDetect.addItem("")
        self.comboBox_SelectDetect.addItem("")
        self.comboBox_SelectDetect.addItem("")
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(710, 510, 691, 141))
        self.groupBox_2.setObjectName("groupBox_2")
        self.pushButton2 = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton2.setGeometry(QtCore.QRect(210, 60, 75, 23))
        self.pushButton2.setObjectName("pushButton2")
        self.pushButton1 = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton1.setGeometry(QtCore.QRect(90, 60, 75, 23))
        self.pushButton1.setObjectName("pushButton1")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1408, 23))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.comboBox_SelectData.currentIndexChanged['int'].connect(MainWindow.onbuttonclick_selectDataType)
        self.pushButton_3Ddetect.clicked.connect(MainWindow.onbuttonclick_videodisplay)
        self.pushButton1.clicked.connect(MainWindow.onbuttonclick_picdetect)
        self.pushButton2.clicked.connect(MainWindow.onbuttonclick_videodetect)
        self.comboBox_SelectDetect.currentIndexChanged['int'].connect(MainWindow.onbuttonclick_selectDetect)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox_AftShow.setTitle(_translate("MainWindow", "测试实例"))
        self.groupBox_PreShow.setTitle(_translate("MainWindow", "输入实例"))
        self.groupBox.setTitle(_translate("MainWindow", "车辆3D检测"))
        self.label_datatype.setText(_translate("MainWindow", "选择数据类型："))
        self.comboBox_SelectData.setItemText(1, _translate("MainWindow", "读入图像"))
        self.comboBox_SelectData.setItemText(2, _translate("MainWindow", "读入本地视频"))
        self.pushButton_3Ddetect.setText(_translate("MainWindow", "检测"))
        self.label_datatype_2.setText(_translate("MainWindow", "二维检测方式："))
        self.comboBox_SelectDetect.setItemText(1, _translate("MainWindow", "Yolov3"))
        self.comboBox_SelectDetect.setItemText(2, _translate("MainWindow", "Yolov4"))
        self.comboBox_SelectDetect.setItemText(3, _translate("MainWindow", "MaskRcnn"))
        self.groupBox_2.setTitle(_translate("MainWindow", "车辆逆投影识别"))
        self.pushButton2.setText(_translate("MainWindow", "预留按钮2"))
        self.pushButton1.setText(_translate("MainWindow", "预留按钮1"))
